name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck

  integration:
    runs-on: ubuntu-latest
    container: cypress/included:6.5.0

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: npm ci
      - run: |
          # Compile JS
          npm run compile
          # Build all examples
          npm run build:basic
          npm run build:customised
          npm run build:sections
          # Check that examples really works: no JS errors on load
          npm run test:browser:pre
          npm run test:browser:basic
          npm run test:browser:customised
          npm run test:browser:sections

  cypress:
    runs-on: ubuntu-latest
    container: cypress/included:6.5.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Prepare styleguidist
        run: |
          npm ci
          npm run compile

      - name: Run integration tests with Cypress
        run: |
          npm run test:cypress:startServer &
          npm run test:cypress:run

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run test:jest -- --runInBand
